### Ajouter un nouveau client
POST http://localhost:5000/api/v1/dettes
Content-Type: application/json
Accept: application/json

{
    "montant": 10000,
    "clientId": 1,
    "articles": [
        {
            "articleId": 1,
            "qteVente": 120,
            "prixVente": 1000
        },
        {
            "articleId": 2,
            "qteVente": 120,
            "prixVente": 1000
        }
    ]
}

###

### Récupérer tous les clients
GET http://localhost:5000/api/v1/clients

###

### Récupérer un client par ID
GET http://localhost:5000/api/v1/clients/1

###

### Récupérer un client par numéro de téléphone
POST http://localhost:5000/api/v1/clients/telephone
Content-Type: application/json
Accept: application/json

{
    "telephone": "772142787"
}
